#ifndef QUERIESH
#define QUERIESH

enum Query
{
	START, SELECT, INSERT, CREATE, TABLE, COLUMNS, FROM, INTO, END, TABLE_VAR, COLUMN_VAR, VALUES_VAR, INSERT_TABLE, INSERT_COLUMNS, CREATE_COLUMNS, CREATE_TABLE, VALUES, UNKNOWN
};

#endif